#!/bin/sh
# description: Reconfigure xpad for BRX dongle

start() {
	echo "303A 81EB" > /sys/bus/usb/drivers/xpad/new_id
	modprobe xpad
}

stop() {
	echo "303A 81EB" > /sys/bus/usb/drivers/xpad/remove_id
	modprobe xpad
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    *)
       echo "Usage: $0 {start|stop|restart}"
esac

exit 0
